### ISSUE TITLE
Response from HomeWizard Energy `api/v1/data` endpoint will be changed

### ISSUE THREAD

**Issue by DCSBL** [nielsdelestinne/homewizard-local-energy#1]
Hello! I am a developer @HomeWizard, and I would like to inform you about a change in the HomeWizard Energy local API;

In 1 or 2 months the local API response will be changed a bit; `NULL` datapoints are not send anymore. See https://homewizard-energy-api.readthedocs.io/changelog.html#id1

Also, _all_ datapoints in `api/v1/data` are now optional. This means that data that is unknown is not send at all. This behaviour is chosen because the API is going to support more datapoints in the near future and we have to be more compatible with different telegrams.

For example, Sweden does not have tariffs and Hungary has 4 different tariffs, currently the API always sends two. In the future the API sends 0 to 4 totals (one for each tariff)

Examples are added to the API documentation [here](https://homewizard-energy-api.readthedocs.io/endpoints.html). If you have any question, feel free to ask!

**Comment by nielsdelestinne** [comment]
Hi @DCSBL, thanks for stopping by & thanks for the update.

Will the [documentation](https://homewizard-energy-api.readthedocs.io/endpoints.html#recent-measurement-api-v1-data) also include a column specifying for which _type_ of telegram the datapoint exists?
- This is interesting to know and (for example) would make it easier for a client to enforce specific expectations related to the datapoints that may be returned (if desired).

Data | Type | Available for meter | Available for telegram | Description |
| -- | -- | -- | -- | -- |
total_power_export_t2_kwh | Number | HWE-P1 | FLU5 (BE), XXX (HU), YYY (SE) | The power feed-in meter reading for tariff 2 in kWh |
total_power_export_t3_kwh | Number | HWE-P1 | XXX (HU) | The power feed-in meter reading for tariff 3 in kWh |

**Comment by DCSBL** [comment]
Hey @nielsdelestinne, good idea. I will add this ASAP.

**Comment by nielsdelestinne** [comment]
> Hey @nielsdelestinne, good idea. I will add this ASAP.

Awesome!

Loving your product by the way. 👍
